// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
  TURSO_DATABASE_URL: string;
  TURSO_AUTH_TOKEN: string;
  TWITCH_CLIENT_ID: string;
}
