// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
  SUPABASE_URL: string;
  SUPABASE_KEY: string;
}
