name: Deploy Server Rewards
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Set Supabase Secrets in Cloudflare Workers
        run: |
          echo "${{ secrets.SUPABASE_URL }}" | wrangler secret put SUPABASE_URL --env production
          echo "${{ secrets.SUPABASE_KEY }}" | wrangler secret put SUPABASE_KEY --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run nx deploy for server-rewards
        run: pnpm nx deploy server-rewards
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
